name = "mytourguide-web"
compatibility_date = "2026-07-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "ADMIN_CONFIG_DB"
database_name = "mytourguide-admin-config"
database_id = "eb9ef100-9d1f-4c1b-b44f-d1187968a3e6"
migrations_dir = "migrations"

[vars]
ADMIN_USERNAME = "admin"
