import { buildPdf, cors, json, reservationSummary } from './_shared.js';

export async function onRequestOptions() {
  return cors();
}

export async function onRequestPost({ request }) {
  const body = await request.json().catch(() => ({}));
  const lines = [
    ...reservationSummary(body),
    `Tarih: ${new Date().toISOString()}`,
    'PDF export generated by My Tour Guide',
  ];
  const pdfBytes = buildPdf(lines);
  return new Response(pdfBytes, {
    status: 200,
    headers: {
      'content-type': 'application/pdf',
      'content-disposition': 'inline; filename="reservation-summary.pdf"',
      'access-control-allow-origin': '*',
    },
  });
}
